Elections project. Goal: to see the affect of proportional distribution of votes within the electoral college rather than "winner take all"

Data needed: 
- election results by state
- elecoral votes per state

# explore the data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
elections = pd.read_csv('president-1976-2016.csv')
elections.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
0,1976,Alabama,AL,1,63,41,US President,"Carter, Jimmy",democrat,False,659170,1182850,20171015,NaN
1,1976,Alabama,AL,1,63,41,US President,"Ford, Gerald",republican,False,504070,1182850,20171015,NaN
2,1976,Alabama,AL,1,63,41,US President,"Maddox, Lester",american independent party,False,9198,1182850,20171015,NaN
3,1976,Alabama,AL,1,63,41,US President,"Bubar, Benjamin """"Ben""""",prohibition,False,6669,1182850,20171015,NaN
4,1976,Alabama,AL,1,63,41,US President,"Hall, Gus",communist party use,False,1954,1182850,20171015,NaN

In [3]:
republican_years = elections[elections['party'] == 'republican']['year']
republican_years.value_counts()

2016    52
2012    51
2008    51
2004    51
2000    51
1996    51
1992    51
1988    51
1984    51
1980    51
1976    51
Name: year, dtype: int64

In [4]:
democrat_years = elections[elections['party'] == 'democrat']['year']
democrat_years.value_counts()

2016    53
2008    51
2004    51
1996    51
1992    51
1988    51
1984    51
1980    51
1976    51
2012    50
2000    50
Name: year, dtype: int64

In [5]:
#remove non-major party candidates
elections_dr = elections[(elections['party'] == 'democrat') | (elections['party'] == 'democratic-farmer-labor') | (elections['party'] == 'republican')]
elections_dr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1126 entries, 0 to 3733
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            1126 non-null   int64
 1   state           1126 non-null   object
 2   state_po        1126 non-null   object
 3   state_fips      1126 non-null   int64
 4   state_cen       1126 non-null   int64
 5   state_ic        1126 non-null   int64
 6   office          1126 non-null   object
 7   candidate       1125 non-null   object
 8   party           1126 non-null   object
 9   writein         1126 non-null   bool
 10  candidatevotes  1126 non-null   int64
 11  totalvotes      1126 non-null   int64
 12  version         1126 non-null   int64
 13  notes           0 non-null      float64
dtypes: bool(1), float64(1), int64(7), object(5)
memory usage: 124.3+ KB

In [6]:
elections_dr[elections_dr['year'] == 2016]

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
3395,2016,Alabama,AL,1,63,41,US President,"Trump, Donald J.",republican,False,1318255,2123372,20171015,NaN
3396,2016,Alabama,AL,1,63,41,US President,"Clinton, Hillary",democrat,False,729547,2123372,20171015,NaN
3400,2016,Alaska,AK,2,94,81,US President,"Trump, Donald J.",republican,False,163387,318608,20171015,NaN
3401,2016,Alaska,AK,2,94,81,US President,"Clinton, Hillary",democrat,False,116454,318608,20171015,NaN
3407,2016,Arizona,AZ,4,86,61,US President,"Trump, Donald J.",republican,False,1252401,2573165,20171015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3719,2016,West Virginia,WV,54,55,56,US President,"Clinton, Hillary",democrat,False,188794,713051,20171015,NaN
3723,2016,Wisconsin,WI,55,35,25,US President,"Trump, Donald J.",republican,False,1405284,2976150,20171015,NaN
3724,2016,Wisconsin,WI,55,35,25,US President,"Clinton, Hillary",democrat,False,1382536,2976150,20171015,NaN
3732,2016,Wyoming,WY,56,83,68,US President,"Trump, Donald J.",republican,False,174419,258788,20171015,NaN
3733,2016,Wyoming,WY,56,83,68,US President,"Clinton, Hillary",democrat,False,55973,258788,20171015,NaN

In [7]:
elections_dr[elections_dr['year'] == 2016]['state'].value_counts()

Maryland                4
Arizona                 3
New Hampshire           2
Montana                 2
Alaska                  2
Utah                    2
South Carolina          2
Kentucky                2
District of Columbia    2
Texas                   2
Kansas                  2
New Jersey              2
Pennsylvania            2
Florida                 2
North Dakota            2
Delaware                2
Wisconsin               2
Virginia                2
Wyoming                 2
Nevada                  2
West Virginia           2
Tennessee               2
Oregon                  2
South Dakota            2
Mississippi             2
Missouri                2
Georgia                 2
Louisiana               2
New Mexico              2
Oklahoma                2
Connecticut             2
Iowa                    2
Minnesota               2
Illinois                2
Indiana                 2
North Carolina          2
Nebraska                2
Ohio                    2
Alabama                 2
Michigan                2
New York                2
Washington              2
Rhode Island            2
Maine                   2
Colorado                2
Arkansas                2
Hawaii                  2
Vermont                 2
Massachusetts           2
Idaho                   2
California              2
Name: state, dtype: int64

In [8]:
#remove writeins
elections_dr_nw = elections_dr[(elections_dr['writein'] == False)]

In [9]:
elections_dr_nw[elections_dr_nw['state'] == 'Minnesota']

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
141,1976,Minnesota,MN,27,41,33,US President,"Carter, Jimmy",democrat,False,1070440,1949931,20171015,NaN
142,1976,Minnesota,MN,27,41,33,US President,"Ford, Gerald",republican,False,819395,1949931,20171015,NaN
493,1980,Minnesota,MN,27,41,33,US President,"Carter, Jimmy",democrat,False,954173,2051916,20171015,NaN
494,1980,Minnesota,MN,27,41,33,US President,"Reagan, Ronald",republican,False,873268,2051916,20171015,NaN
840,1984,Minnesota,MN,27,41,33,US President,"Mondale, Walter",democrat,False,1036364,2084449,20171015,NaN
841,1984,Minnesota,MN,27,41,33,US President,"Reagan, Ronald",republican,False,1032603,2084449,20171015,NaN
1141,1988,Minnesota,MN,27,41,33,US President,"Dukakis, Michael",democrat,False,1109471,2096790,20171015,NaN
1142,1988,Minnesota,MN,27,41,33,US President,"Bush, George H.W.",republican,False,962337,2096790,20171015,NaN
1474,1992,Minnesota,MN,27,41,33,US President,"Clinton, Bill",democrat,False,1020997,2347948,20171015,NaN
1475,1992,Minnesota,MN,27,41,33,US President,"Bush, George H.W.",republican,False,747841,2347948,20171015,NaN
1846,1996,Minnesota,MN,27,41,33,US President,"Clinton, Bill",democrat,False,1120380,2192492,20171015,NaN
1847,1996,Minnesota,MN,27,41,33,US President,"Dole, Robert",republican,False,766395,2192492,20171015,NaN
2210,2000,Minnesota,MN,27,41,33,US President,"Gore, Al",democratic-farmer-labor,False,1168266,2438685,20171015,NaN
2211,2000,Minnesota,MN,27,41,33,US President,"Bush, George W.",republican,False,1109659,2438685,20171015,NaN
2559,2004,Minnesota,MN,27,41,33,US President,"Kerry, John",democratic-farmer-labor,False,1445014,2828387,20171015,NaN
2560,2004,Minnesota,MN,27,41,33,US President,"Bush, George W.",republican,False,1346695,2828387,20171015,NaN
2892,2008,Minnesota,MN,27,41,33,US President,"Obama, Barack H.",democrat,False,1573354,2910369,20171015,NaN
2893,2008,Minnesota,MN,27,41,33,US President,"McCain, John",republican,False,1275409,2910369,20171015,NaN
3225,2012,Minnesota,MN,27,41,33,US President,"Obama, Barack H.",democratic-farmer-labor,False,1546167,2936561,20171015,NaN
3226,2012,Minnesota,MN,27,41,33,US President,"Romney, Mitt",republican,False,1320225,2936561,20171015,NaN
3558,2016,Minnesota,MN,27,41,33,US President,"Clinton, Hillary",democrat,False,1367705,2944782,20171015,NaN
3559,2016,Minnesota,MN,27,41,33,US President,"Trump, Donald J.",republican,False,1322949,2944782,20171015,NaN

In [10]:
elections_dr_nw['state'].value_counts()

Florida                 22
New Hampshire           22
Missouri                22
Montana                 22
New York                22
South Carolina          22
Kentucky                22
District of Columbia    22
Texas                   22
Kansas                  22
New Jersey              22
Pennsylvania            22
Delaware                22
New Mexico              22
Alaska                  22
Virginia                22
Wyoming                 22
Nevada                  22
Utah                    22
West Virginia           22
Tennessee               22
Oregon                  22
South Dakota            22
Mississippi             22
Louisiana               22
Idaho                   22
Georgia                 22
Alabama                 22
Oklahoma                22
Connecticut             22
Iowa                    22
Minnesota               22
Illinois                22
Indiana                 22
North Carolina          22
Nebraska                22
Arizona                 22
Ohio                    22
Maryland                22
Massachusetts           22
Michigan                22
Wisconsin               22
North Dakota            22
Washington              22
Rhode Island            22
Maine                   22
Colorado                22
Arkansas                22
Hawaii                  22
Vermont                 22
California              22
Name: state, dtype: int64

In [11]:
elections[elections['writein'] == True].sort_values(by='candidatevotes', ascending=False).head(20)

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
3429,2016,California,CA,6,93,71,US President,NaN,NaN,True,120739,14181595,20171015,NaN
3713,2016,Washington,WA,53,91,73,US President,NaN,NaN,True,107805,3317019,20171015,NaN
3688,2016,Texas,TX,48,74,49,US President,NaN,NaN,True,51261,8969226,20171015,NaN
3636,2016,North Carolina,NC,37,56,47,US President,Scattering,NaN,True,47386,4741564,20171015,NaN
3539,2016,Maryland,MD,24,52,52,US President,NaN,NaN,True,33263,2781446,20171015,NaN
3708,2016,Virginia,VA,51,54,40,US President,NaN,NaN,True,31870,3982752,20171015,NaN
3563,2016,Minnesota,MN,27,41,33,US President,NaN,NaN,True,27247,2944782,20171015,NaN
3104,2012,California,CA,6,93,71,US President,NaN,NaN,True,23249,13038547,20171015,NaN
3697,2016,Vermont,VT,50,13,6,US President,NaN,NaN,True,22899,320467,20171015,NaN
3477,2016,Georgia,GA,13,58,44,US President,NaN,NaN,True,22359,4114732,20171015,NaN
3398,2016,Alabama,AL,1,63,41,US President,NaN,NaN,True,21712,2123372,20171015,NaN
2438,2004,California,CA,6,93,71,US President,Other,NaN,True,20854,12421353,20171015,NaN
2757,2008,California,CA,6,93,71,US President,NaN,independent,True,20236,13561900,20171015,NaN
2144,2000,Indiana,IN,18,32,22,US President,NaN,NaN,True,18997,2199302,20171015,NaN
3505,2016,Iowa,IA,19,42,31,US President,NaN,NaN,True,17746,1565580,20171015,NaN
3411,2016,Arizona,AZ,4,86,61,US President,NaN,independent,True,17473,2573165,20171015,NaN
3649,2016,Ohio,OH,39,31,24,US President,NaN,NaN,True,16314,5496487,20171015,NaN
3589,2016,Nebraska,NE,31,46,35,US President,NaN,NaN,True,16051,844227,20171015,NaN
3683,2016,Tennessee,TN,47,62,54,US President,NaN,NaN,True,13789,2508027,20171015,NaN
3494,2016,Illinois,IL,17,33,21,US President,NaN,NaN,True,13282,5536424,20171015,NaN

#clean the data

In [12]:
#remove writeins and unnecessary columns
columns = ['year', 'state', 'candidate', 'party', 'candidatevotes', 'totalvotes']
elections_nw = elections[elections['writein'] == False]
elections_nw = elections_nw[columns]
elections_nw.head()

,year,state,candidate,party,candidatevotes,totalvotes
0,1976,Alabama,"Carter, Jimmy",democrat,659170,1182850
1,1976,Alabama,"Ford, Gerald",republican,504070,1182850
2,1976,Alabama,"Maddox, Lester",american independent party,9198,1182850
3,1976,Alabama,"Bubar, Benjamin """"Ben""""",prohibition,6669,1182850
4,1976,Alabama,"Hall, Gus",communist party use,1954,1182850

In [13]:
#consolidate non-dem and non-rep to one category
elections_nw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3493 entries, 0 to 3739
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            3493 non-null   int64
 1   state           3493 non-null   object
 2   candidate       3427 non-null   object
 3   party           3375 non-null   object
 4   candidatevotes  3493 non-null   int64
 5   totalvotes      3493 non-null   int64
dtypes: int64(3), object(3)
memory usage: 191.0+ KB

In [14]:
elections_nw[elections_nw['party'].isnull()]['candidate'].value_counts()

Other                              58
Scattering                         17
Blank Vote/Scattering              14
Blank Vote                         12
Over Vote                           8
None Of These Candidates            3
Void Vote                           2
None Of The Above                   2
Blank Vote/Void Vote/Scattering     1
Not Designated                      1
Name: candidate, dtype: int64

In [15]:
#remove null party rows as they are similar to writeins
elections_nw = elections_nw[elections_nw['party'].notnull()]
elections_nw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3375 entries, 0 to 3738
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            3375 non-null   int64
 1   state           3375 non-null   object
 2   candidate       3309 non-null   object
 3   party           3375 non-null   object
 4   candidatevotes  3375 non-null   int64
 5   totalvotes      3375 non-null   int64
dtypes: int64(3), object(3)
memory usage: 184.6+ KB

In [16]:
non_mp = elections_nw[(elections_nw['party'] != 'democrat') & (elections_nw['party'] != 'republican')]
non_mp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2256 entries, 2 to 3738
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            2256 non-null   int64
 1   state           2256 non-null   object
 2   candidate       2190 non-null   object
 3   party           2256 non-null   object
 4   candidatevotes  2256 non-null   int64
 5   totalvotes      2256 non-null   int64
dtypes: int64(3), object(3)
memory usage: 123.4+ KB

In [17]:
'''
non_mp['candidate'] = 'other'
non_mp['party'] = 'other'
new_df = []
#arrays = [non_mp['year'].tolist(),non_mp['state_po'].tolist()]
#index = pd.MultiIndex.from_arrays(arrays, names=('year', 'state_po'))
#new_df = non_mp.set_index(index)
aggregate_functions = {'candidate': 'first', 'party': 'first', 'candidatevotes' : 'sum', 'totalvotes' : 'first'}
new_df = non_mp.groupby(['year','state']).aggregate(aggregate_functions)
new_df.head()
'''

"\nnon_mp['candidate'] = 'other'\nnon_mp['party'] = 'other'\nnew_df = []\n#arrays = [non_mp['year'].tolist(),non_mp['state_po'].tolist()]\n#index = pd.MultiIndex.from_arrays(arrays, names=('year', 'state_po'))\n#new_df = non_mp.set_index(index)\naggregate_functions = {'candidate': 'first', 'party': 'first', 'candidatevotes' : 'sum', 'totalvotes' : 'first'}\nnew_df = non_mp.groupby(['year','state']).aggregate(aggregate_functions)\nnew_df.head()\n"

In [18]:
'''
new_df.reset_index(inplace=True)
new_df.head()
'''

'\nnew_df.reset_index(inplace=True)\nnew_df.head()\n'

In [19]:
'''
mp = elections_nw[(elections_nw['party'] == 'democrat') | (elections['party'] == 'democratic-farmer-labor') | (elections_nw['party'] == 'republican')]
elections_df = mp.append(new_df, ignore_index=True)
elections_df.head()
'''

"\nmp = elections_nw[(elections_nw['party'] == 'democrat') | (elections['party'] == 'democratic-farmer-labor') | (elections_nw['party'] == 'republican')]\nelections_df = mp.append(new_df, ignore_index=True)\nelections_df.head()\n"

In [20]:
#elections_df.info()

In [21]:
'''
elections_df = elections_df.sort_values(['year','state']).reset_index(drop=True)
elections_df.head(10)
'''

"\nelections_df = elections_df.sort_values(['year','state']).reset_index(drop=True)\nelections_df.head(10)\n"

In [22]:
null_candidates = elections_nw[elections_nw['candidate'].isnull()]
null_candidates['pct_vote'] = null_candidates['candidatevotes'] / null_candidates['totalvotes']
null_candidates[null_candidates['pct_vote'] > 0.05]
#elections_df = elections_nw

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote
1676,1996,Alabama,NaN,independent,95030,1534349,0.061935
1860,1996,Mississippi,NaN,independent,53427,893857,0.059771
1897,1996,New Jersey,NaN,independent,320400,3075860,0.104166
1974,1996,South Dakota,NaN,independent,32478,323826,0.100295
1978,1996,Tennessee,NaN,independent,121239,1894105,0.064009

In [23]:
elections_nw['candidate'] = elections_nw['candidate'].fillna('other')
elections_df = elections_nw
elections_df.head()

,year,state,candidate,party,candidatevotes,totalvotes
0,1976,Alabama,"Carter, Jimmy",democrat,659170,1182850
1,1976,Alabama,"Ford, Gerald",republican,504070,1182850
2,1976,Alabama,"Maddox, Lester",american independent party,9198,1182850
3,1976,Alabama,"Bubar, Benjamin """"Ben""""",prohibition,6669,1182850
4,1976,Alabama,"Hall, Gus",communist party use,1954,1182850

In [24]:
#determine percentage of vote share
elections_df['pct_vote'] = elections_df['candidatevotes'] / elections_df['totalvotes']
elections_df.head()

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote
0,1976,Alabama,"Carter, Jimmy",democrat,659170,1182850,0.557273
1,1976,Alabama,"Ford, Gerald",republican,504070,1182850,0.426149
2,1976,Alabama,"Maddox, Lester",american independent party,9198,1182850,0.007776
3,1976,Alabama,"Bubar, Benjamin """"Ben""""",prohibition,6669,1182850,0.005638
4,1976,Alabama,"Hall, Gus",communist party use,1954,1182850,0.001652

In [25]:
#electoral votes by year
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/United_States_Electoral_College"
r = requests.get(url)
r_html = r.text
soup = BeautifulSoup(r_html, 'lxml')
tables = soup.find_all('table')
table = tables[4]

new_table = pd.DataFrame(columns=range(0,36), index=range(0,56))
table_head = pd.DataFrame(columns=range(0,36), index=range(0,3))
row_marker = 0
for row in table.find_all('tr'):
    column_marker = 0
    columns = row.find_all(['th','td'])
    for column in columns:
        if row_marker < 3:
            table_head.iloc[row_marker,column_marker] = column.text.replace('\n','')
            #print(column.text.replace('\n',''))
            column_marker += 1
        else:
            new_table.iloc[row_marker,column_marker] = column.text.replace('\n','')
            #print(column.text.replace('\n','')+' '+str(row_marker)+','+str(column_marker))
            column_marker += 1
    row_marker += 1
        
new_table = new_table[4:].drop(columns = 0)
new_table.head()

,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
4,Alabama,,,,,,,3,5,7,...,11,11,11,11,10,9,9,9,9,9
5,Alaska,,,,,,,,,,...,,,,3,3,3,3,3,3,3
6,Arizona,,,,,,,,,,...,3,4,4,4,5,6,7,8,10,11
7,Arkansas,,,,,,,,,,...,9,9,8,8,6,6,6,6,6,6
8,California,,,,,,,,,,...,22,25,32,32,40,45,47,54,55,55

In [26]:
table_index = table_head.iloc[1].to_list()
table_index.insert(0, 'State')
index_dict = {}
for i in range(0,len(table_index)):
    index_dict[i+1] = table_index[i]
new_table = new_table.rename(columns = index_dict).reset_index(drop=True).drop(51)
new_table.tail()

,State,'88,'92,'96'00,'04'08,'12,'16,'20,'24'28,'32,...,'32'36'40,'44'48,'52'56,'60,'64'68,'72'76'80,'84'88,'92'96'00,'04'08,'12'16'20
46,Virginia,12,21,21,24,25,25,25,24,23,...,11,11,12,12,12,12,12,13,13,13
47,Washington,,,,,,,,,,...,8,8,9,9,9,9,10,11,11,12
48,West Virginia,,,,,,,,,,...,8,8,8,8,7,6,6,5,5,5
49,Wisconsin,,,,,,,,,,...,12,12,12,12,12,11,11,11,10,10
50,Wyoming,,,,,,,,,,...,3,3,3,3,3,3,3,3,3,3

In [27]:
ec_votes = new_table.iloc[:,np.r_[0,-5:0]]
ec_votes.head()

        State '72'76'80 '84'88 '92'96'00 '04'08 '12'16'20
0     Alabama         9      9         9      9         9
1      Alaska         3      3         3      3         3
2     Arizona         6      7         8     10        11
3    Arkansas         6      6         6      6         6
4  California        45     47        54     55        55

In [28]:
#check state and year. if state & year match state and 'year, set two equal
years = elections_df['year'].unique()
for year in years:
    if year > 1970 and year <= 1980:
        ec_votes[year] = ec_votes["'72'76'80"]
    elif year > 1980 and year <= 1990:
        ec_votes[year] = ec_votes["'84'88"]
    elif year > 1990 and year <= 2000:
        ec_votes[year] = ec_votes["'92'96'00"]
    elif year > 2000 and year <= 2010:
        ec_votes[year] = ec_votes["'04'08"]
    else:
        ec_votes[year] = ec_votes["'12'16'20"]

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [29]:
ec_votes = ec_votes.drop(columns = table_index[-7:-2]).set_index('State').rename(index={'D.C.':'District of Columbia'})
ec_votes.head()

           1976 1980 1984 1988 1992 1996 2000 2004 2008 2012 2016
State
Alabama       9    9    9    9    9    9    9    9    9    9    9
Alaska        3    3    3    3    3    3    3    3    3    3    3
Arizona       6    6    7    7    8    8    8   10   10   11   11
Arkansas      6    6    6    6    6    6    6    6    6    6    6
California   45   45   47   47   54   54   54   55   55   55   55

In [30]:
elections_df = elections_df.reset_index(drop=True)
for i in range(len(elections_df)):
    elections_df.loc[i,'state_electoral_votes'] = ec_votes.loc[elections_df.loc[i,'state'], elections_df.loc[i,'year']]
elections_df[elections_df['state'] == 'Arizona']

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote,state_electoral_votes
9,1976,Arizona,"Ford, Gerald",republican,418642,742719,0.563661,6
10,1976,Arizona,"Carter, Jimmy",democrat,295602,742719,0.398000,6
11,1976,Arizona,"McCarthy, Eugene """"Gene""""",independent,19229,742719,0.025890,6
12,1976,Arizona,"Macbride, Roger",libertarian,7647,742719,0.010296,6
13,1976,Arizona,"Camejo, Peter",socialist workers,928,742719,0.001249,6
14,1976,Arizona,"Anderson, Thomas J.",american,564,742719,0.000759,6
15,1976,Arizona,"Maddox, Lester",american independent party,85,742719,0.000114,6
322,1980,Arizona,"Reagan, Ronald",republican,529688,873945,0.606088,6
323,1980,Arizona,"Carter, Jimmy",democrat,246843,873945,0.282447,6
324,1980,Arizona,"Anderson, John B.",independent,76952,873945,0.088051,6
325,1980,Arizona,"Clark, Edward """"Ed""""",libertarian,18784,873945,0.021493,6
326,1980,Arizona,"Deberry, Clifton",socialist workers,1100,873945,0.001259,6
327,1980,Arizona,"Commoner, Barry",citizens,551,873945,0.000630,6
328,1980,Arizona,"Hall, Gus",communist party use,25,873945,0.000029,6
329,1980,Arizona,"Griswold, Deirdre",workers world,2,873945,0.000002,6
664,1984,Arizona,"Reagan, Ronald",republican,681416,1025897,0.664215,7
665,1984,Arizona,"Mondale, Walter",democrat,333854,1025897,0.325426,7
666,1984,Arizona,"Bergland, David",libertarian,10585,1025897,0.010318,7
966,1988,Arizona,"Bush, George H.W.",republican,702541,1171873,0.599503,7
967,1988,Arizona,"Dukakis, Michael",democrat,454029,1171873,0.387439,7
968,1988,Arizona,"Paul, Ronald """"Ron""""",libertarian,13351,1171873,0.011393,7
969,1988,Arizona,"Fulani, Lenora",new alliance,1662,1171873,0.001418,7
1236,1992,Arizona,"Bush, George H.W.",republican,572086,1486975,0.384731,8
1237,1992,Arizona,"Clinton, Bill",democrat,543050,1486975,0.365205,8
1238,1992,Arizona,"Perot, Ross",independent,353741,1486975,0.237893,8
1239,1992,Arizona,"Gritz, James """"Bo""""",independent,8141,1486975,0.005475,8
1240,1992,Arizona,"Marrou, Andre",libertarian,6759,1486975,0.004545,8
1241,1992,Arizona,"Hagelin, John",natural law,2267,1486975,0.001525,8
1242,1992,Arizona,"Fulani, Lenora",new alliance,923,1486975,0.000621,8
1576,1996,Arizona,"Clinton, Bill",democrat,653288,1404405,0.465171,8
1577,1996,Arizona,"Dole, Robert",republican,622073,1404405,0.442944,8
1578,1996,Arizona,"Perot, Ross",reform party,112072,1404405,0.079800,8
1579,1996,Arizona,"Browne, Harry",libertarian,14358,1404405,0.010224,8
1914,2000,Arizona,"Bush, George W.",republican,781652,1532016,0.510211,8
1915,2000,Arizona,"Gore, Al",democrat,685341,1532016,0.447346,8
1916,2000,Arizona,"Nader, Ralph",green,45645,1532016,0.029794,8
1917,2000,Arizona,"Buchanan, Patrick """"Pat""""",reform party,12373,1532016,0.008076,8
1918,2000,Arizona,"L. Neil, Smith",libertarian,5775,1532016,0.003770,8
1919,2000,Arizona,"Hagelin, John",natural law,1120,1532016,0.000731,8
2247,2004,Arizona,"Bush, George W.",republican,1104294,2012585,0.548694,10
2248,2004,Arizona,"Kerry, John",democrat,893524,2012585,0.443968,10
2249,2004,Arizona,"Badnarik, Michael",libertarian,11856,2012585,0.005891,10
2520,2008,Arizona,"McCain, John",republican,1230111,2293475,0.536352,10
2521,2008,Arizona,"Obama, Barack H.",democrat,1034707,2293475,0.451153,10
2522,2008,Arizona,"Barr, Bob",libertarian,12555,2293475,0.005474,10
2523,2008,Arizona,"Nader, Ralph",independent,11301,2293475,0.004927,10
2524,2008,Arizona,"McKinney, Cynthia",green,3406,2293475,0.001485,10
2826,2012,Arizona,"Romney, Mitt",republican,1233654,2299254,0.536545,11
2827,2012,Arizona,"Obama, Barack H.",democrat,1025232,2299254,0.445898,11
2828,2012,Arizona,"Johnson, Gary",libertarian,32100,2299254,0.013961,11
2829,2012,Arizona,"Stein, Jill",green,7816,2299254,0.003399,11
3104,2016,Arizona,"Trump, Donald J.",republican,1252401,2573165,0.486716,11
3105,2016,Arizona,"Clinton, Hillary",democrat,1161167,2573165,0.451260,11
3106,2016,Arizona,"Johnson, Gary",libertarian,106327,2573165,0.041321,11
3107,2016,Arizona,"Stein, Jill",green,34345,2573165,0.013347,11

In [31]:
elections_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375 entries, 0 to 3374
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   3375 non-null   int64
 1   state                  3375 non-null   object
 2   candidate              3375 non-null   object
 3   party                  3375 non-null   object
 4   candidatevotes         3375 non-null   int64
 5   totalvotes             3375 non-null   int64
 6   pct_vote               3375 non-null   float64
 7   state_electoral_votes  3375 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 211.1+ KB

In [32]:
elections_df['state_electoral_votes'] = elections_df['state_electoral_votes'].astype(int)
elections_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3375 entries, 0 to 3374
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   3375 non-null   int64
 1   state                  3375 non-null   object
 2   candidate              3375 non-null   object
 3   party                  3375 non-null   object
 4   candidatevotes         3375 non-null   int64
 5   totalvotes             3375 non-null   int64
 6   pct_vote               3375 non-null   float64
 7   state_electoral_votes  3375 non-null   int64
dtypes: float64(1), int64(4), object(3)
memory usage: 211.1+ KB

In [33]:
#elections_df['candidate_evs'] = elections_df.apply(lambda x: (x['state_electoral_votes'] * x['pct_vote'] if x['pct_vote'] >= 0.05 else 0), axis=1)
elections_df['candidate_evs'] = elections_df['state_electoral_votes'] * elections_df['pct_vote'] 
elections_df.head(20)

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote,state_electoral_votes,candidate_evs
0,1976,Alabama,"Carter, Jimmy",democrat,659170,1182850,0.557273,9,5.015454
1,1976,Alabama,"Ford, Gerald",republican,504070,1182850,0.426149,9,3.835338
2,1976,Alabama,"Maddox, Lester",american independent party,9198,1182850,0.007776,9,0.069985
3,1976,Alabama,"Bubar, Benjamin """"Ben""""",prohibition,6669,1182850,0.005638,9,0.050743
4,1976,Alabama,"Hall, Gus",communist party use,1954,1182850,0.001652,9,0.014867
5,1976,Alabama,"Macbride, Roger",libertarian,1481,1182850,0.001252,9,0.011269
6,1976,Alaska,"Ford, Gerald",republican,71555,123574,0.579046,3,1.737137
7,1976,Alaska,"Carter, Jimmy",democrat,44058,123574,0.356531,3,1.069594
8,1976,Alaska,"Macbride, Roger",libertarian,6785,123574,0.054906,3,0.164719
9,1976,Arizona,"Ford, Gerald",republican,418642,742719,0.563661,6,3.381968
10,1976,Arizona,"Carter, Jimmy",democrat,295602,742719,0.398000,6,2.387999
11,1976,Arizona,"McCarthy, Eugene """"Gene""""",independent,19229,742719,0.025890,6,0.155340
12,1976,Arizona,"Macbride, Roger",libertarian,7647,742719,0.010296,6,0.061776
13,1976,Arizona,"Camejo, Peter",socialist workers,928,742719,0.001249,6,0.007497
14,1976,Arizona,"Anderson, Thomas J.",american,564,742719,0.000759,6,0.004556
15,1976,Arizona,"Maddox, Lester",american independent party,85,742719,0.000114,6,0.000687
16,1976,Arkansas,"Carter, Jimmy",democrat,498604,767535,0.649617,6,3.897704
17,1976,Arkansas,"Ford, Gerald",republican,267903,767535,0.349043,6,2.094260
18,1976,Arkansas,other,independent,639,767535,0.000833,6,0.004995
19,1976,Arkansas,"Maddox, Lester",american independent party,389,767535,0.000507,6,0.003041

In [34]:
elections_df['candidate_evs_round'] = round(elections_df['candidate_evs'],0)
elections_df.head(20)

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote,state_electoral_votes,candidate_evs,candidate_evs_round
0,1976,Alabama,"Carter, Jimmy",democrat,659170,1182850,0.557273,9,5.015454,5.0
1,1976,Alabama,"Ford, Gerald",republican,504070,1182850,0.426149,9,3.835338,4.0
2,1976,Alabama,"Maddox, Lester",american independent party,9198,1182850,0.007776,9,0.069985,0.0
3,1976,Alabama,"Bubar, Benjamin """"Ben""""",prohibition,6669,1182850,0.005638,9,0.050743,0.0
4,1976,Alabama,"Hall, Gus",communist party use,1954,1182850,0.001652,9,0.014867,0.0
5,1976,Alabama,"Macbride, Roger",libertarian,1481,1182850,0.001252,9,0.011269,0.0
6,1976,Alaska,"Ford, Gerald",republican,71555,123574,0.579046,3,1.737137,2.0
7,1976,Alaska,"Carter, Jimmy",democrat,44058,123574,0.356531,3,1.069594,1.0
8,1976,Alaska,"Macbride, Roger",libertarian,6785,123574,0.054906,3,0.164719,0.0
9,1976,Arizona,"Ford, Gerald",republican,418642,742719,0.563661,6,3.381968,3.0
10,1976,Arizona,"Carter, Jimmy",democrat,295602,742719,0.398000,6,2.387999,2.0
11,1976,Arizona,"McCarthy, Eugene """"Gene""""",independent,19229,742719,0.025890,6,0.155340,0.0
12,1976,Arizona,"Macbride, Roger",libertarian,7647,742719,0.010296,6,0.061776,0.0
13,1976,Arizona,"Camejo, Peter",socialist workers,928,742719,0.001249,6,0.007497,0.0
14,1976,Arizona,"Anderson, Thomas J.",american,564,742719,0.000759,6,0.004556,0.0
15,1976,Arizona,"Maddox, Lester",american independent party,85,742719,0.000114,6,0.000687,0.0
16,1976,Arkansas,"Carter, Jimmy",democrat,498604,767535,0.649617,6,3.897704,4.0
17,1976,Arkansas,"Ford, Gerald",republican,267903,767535,0.349043,6,2.094260,2.0
18,1976,Arkansas,other,independent,639,767535,0.000833,6,0.004995,0.0
19,1976,Arkansas,"Maddox, Lester",american independent party,389,767535,0.000507,6,0.003041,0.0

In [35]:
elections_non_mp = elections_df[(elections_df['party'] != 'democrat') & (elections_df['party'] != 'republican') & (elections_df['party'] != 'democratic-farmer-labor')]
elections_non_mp[elections_non_mp['candidate_evs_round'] > 0]

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote,state_electoral_votes,candidate_evs,candidate_evs_round
191,1976,New York,"Ford, Gerald",conservative,274878,6668262,0.041222,41,1.690095,2.0
192,1976,New York,"Carter, Jimmy",liberal party,145393,6668262,0.021804,41,0.893953,1.0
324,1980,Arizona,"Anderson, John B.",independent,76952,873945,0.088051,6,0.528308,1.0
339,1980,California,"Anderson, John B.",independent,739618,8582938,0.086173,45,3.877788,4.0
340,1980,California,"Clark, Edward """"Ed""""",libertarian,148390,8582938,0.017289,45,0.778003,1.0
...,...,...,...,...,...,...,...,...,...,...
3281,2016,New York,"Clinton, Hillary",working families,140041,7802084,0.017949,29,0.520526,1.0
3297,2016,Ohio,other,no party affiliation,198733,5496487,0.036156,18,0.650815,1.0
3332,2016,Texas,"Johnson, Gary",libertarian,283492,8969226,0.031607,38,1.201073,1.0
3336,2016,Utah,"McMullin, Evan",no party affiliation,255060,1131317,0.225454,6,1.352724,1.0
3353,2016,Washington,"Johnson, Gary",libertarian,160879,3317019,0.048501,12,0.582013,1.0

In [36]:
calc_evs = elections_df[['year','state','candidate_evs_round']].groupby(['year','state']).sum().reset_index(drop=False)
calc_evs

     year          state  candidate_evs_round
0    1976        Alabama                  9.0
1    1976         Alaska                  3.0
2    1976        Arizona                  5.0
3    1976       Arkansas                  6.0
4    1976     California                 44.0
..    ...            ...                  ...
556  2016       Virginia                 12.0
557  2016     Washington                 11.0
558  2016  West Virginia                  4.0
559  2016      Wisconsin                 10.0
560  2016        Wyoming                  3.0

[561 rows x 3 columns]

In [37]:
elections_df[(elections_df['year'] == 1992) & (elections_df['state'] == 'Georgia')]

,year,state,candidate,party,candidatevotes,totalvotes,pct_vote,state_electoral_votes,candidate_evs,candidate_evs_round
1285,1992,Georgia,"Clinton, Bill",democrat,1008966,2321133,0.434687,13,5.650929,6.0
1286,1992,Georgia,"Bush, George H.W.",republican,995252,2321133,0.428779,13,5.574121,6.0
1287,1992,Georgia,"Perot, Ross",independent,309657,2321133,0.133408,13,1.734300,2.0
1288,1992,Georgia,"Marrou, Andre",libertarian,7110,2321133,0.003063,13,0.039821,0.0

In [38]:
# get total number of actual evs per state per election year

ev_by_state = elections_df[['year','state','state_electoral_votes']].groupby(['year','state']).first().reset_index(drop=False)
ev_by_state

     year          state  state_electoral_votes
0    1976        Alabama                      9
1    1976         Alaska                      3
2    1976        Arizona                      6
3    1976       Arkansas                      6
4    1976     California                     45
..    ...            ...                    ...
556  2016       Virginia                     13
557  2016     Washington                     12
558  2016  West Virginia                      5
559  2016      Wisconsin                     10
560  2016        Wyoming                      3

[561 rows x 3 columns]

In [39]:
ev_comp = pd.merge(calc_evs, ev_by_state, how='left', on=['year','state'])
ev_comp

     year          state  candidate_evs_round  state_electoral_votes
0    1976        Alabama                  9.0                      9
1    1976         Alaska                  3.0                      3
2    1976        Arizona                  5.0                      6
3    1976       Arkansas                  6.0                      6
4    1976     California                 44.0                     45
..    ...            ...                  ...                    ...
556  2016       Virginia                 12.0                     13
557  2016     Washington                 11.0                     12
558  2016  West Virginia                  4.0                      5
559  2016      Wisconsin                 10.0                     10
560  2016        Wyoming                  3.0                      3

[561 rows x 4 columns]

In [40]:
#if Match == False --> calculate match

def adjust_evs(row):
    if row['state_electoral_votes'] != row['candidate_evs_round']:
        if row['state_electoral_votes'] > row['candidate_evs_round']: 
            year = row['year']
            state = row['state']
            temp_df =  elections_df[(elections_df['year'] == year) & (elections_df['state'] == state)].reset_index(drop = True)
            temp_dict = {}
            total_evs = temp_df.loc[0,'state_electoral_votes']
            for index, row in temp_df.iterrows():
                candidate = row['candidate']
                candidate_evs = row['candidate_evs_round']
                calculated_evs = row['candidate_evs']
                distance = calculated_evs - candidate_evs
                temp_dict[candidate] = distance
            winner = max(temp_dict, key=temp_dict.get)
            row['candidate_evs_round'] += 1
            elections_df.loc[elections_df[(elections_df['year'] == year) & (elections_df['state'] == state) & (elections_df['candidate'] == winner)].index, 'candidate_evs_round'] += 1
            return adjust_evs(row)
        else:
            year = row['year']
            state = row['state']
            temp_df =  elections_df[(elections_df['year'] == year) & (elections_df['state'] == state)]
            temp_dict = {}
            total_evs = temp_df.loc[0,'state_electoral_votes']
            for index, row in temp_df.iterrows():
                candidate = row['candidate']
                candidate_evs = row['candidate_evs_round']
                calculated_evs = row['candidate_evs']
                distance = calculated_evs - candidate_evs
                temp_dict[candidate] = distance
            winner = min(temp_dict, key=temp_dict.get)
            row['candidate_evs_round'] -= 1
            elections_df.loc[elections_df[(elections_df['year'] == year) & (elections_df['state'] == state) & (elections_df['candidate'] == winner)].index, 'candidate_evs_round'] -= 1
            return adjust_evs(row)
    else:
        return

ev_comp['candidate_evs_round'] = ev_comp.apply(lambda x: adjust_evs(x), axis=1)

#for index, row in ev_comp.iterrows():
#    print(row['year'], row['state'])

KeyError: 0

In [ ]:
ev_comp

In [ ]:
elections_df.head(20)

In [ ]:
#elections_df[(elections_df['year'] == 1976) & (elections_df['state'] == 'Arizona') & (elections_df['candidate'] == 'Carter, Jimmy')]['candidate_evs_round']
elections_df.loc[elections_df[(elections_df['year'] == 1976) & (elections_df['state'] == 'Arizona') & (elections_df['candidate'] == 'Carter, Jimmy')].index, 'candidate_evs_round'] += 1
elections_df[(elections_df['year'] == 1976) & (elections_df['state'] == 'Arizona') & (elections_df['candidate'] == 'Carter, Jimmy')]['candidate_evs_round']